### ISSUE TITLE
MSWINSCK.OCX missing on win 10

### ISSUE THREAD

**Issue by siftuser** [dzzie/MAP#5]
Win 10 does not contain the dependency MSWINSCK.OCX. Any help ? Thank you

**Comment by dzzie** [comment]
Hi, did you run the installer?
http://sandsprite.com/CodeStuff/map_setup.exe

The OCX is included and should be registered automatically. 
https://github.com/dzzie/MAP/blob/master/install_script.iss#L19

If not, did you get any AV popups maybe something blocked it?

**Comment by siftuser** [comment]
Thanks @dzzie 

No I did not ... as I could download mail_pot.exe from github. 

Is this hash correct  72859c2cd4df4a767abb16bd47893be007e78196fb6193127b647e18b2b9efda ? as VT shows multiple alerts

https://www.virustotal.com/gui/file/72859c2cd4df4a767abb16bd47893be007e78196fb6193127b647e18b2b9efda/details

**Comment by dzzie** [comment]
thats the same hash I have on this PC when I mirrored my site on 3/20/2020. My primary PC is down in FL right now. I have personally run the installer since then here. AV is notoriously bad when it comes to false positive on VB6 executables.

If you dont want to run the installer, you can download the whole git repo and then manually register the files in the /dependencies folder. You will need to use a _32bit_ version of cmd.exe (from SysWow64 folder) run as admin, then regsvr32.exe <filename> all of the dlls and ocxs. I just make a batch file from a dir /b listing. You can skip utypes.dll its not an activex dll.

regsvr32 hexed.ocx
regsvr32 libVT.dll
regsvr32 mscomctl.ocx
regsvr32 MSINET.OCX
regsvr32 MSWINSCK.OCX
regsvr32 RICHTX32.OCX
regsvr32 sppe3.dll
regsvr32 spSubclass2.dll
regsvr32 TLBINF32.DLL
regsvr32 vbDevKit.dll
regsvr32 vbUtypes.dll

Or run it in a virtual machine and play with it. I have given up on trying to keep 50+ AV straight. I submit stuff as false positives, its fine for a while, then I get more..cant keep up with it.

**Comment by siftuser** [comment]
> thats the same hash I have on this PC when I mirrored my site on 3/20/2020. My primary PC is down in FL right now. I have personally run the installer since then here. AV is notoriously bad when it comes to false positive on VB6 executables.

Thank you for reassuring ... just wanted to make sure I got it right.



> I have given up on trying to keep 70+ AV straight. I submit stuff as false positives, its fine for a while, then I get more..cant keep up with it. Kaspersky's detection is generally my golden standard of which one to believe.

Understandable :) Thank you for your help
